# Generated by Django 3.2.6 on 2021-09-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
