# Generated by Django 3.2.6 on 2021-09-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_1', '0002_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
