# Generated by Django 3.2.6 on 2021-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_1', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_source', models.CharField(max_length=200)),
                ('url_source', models.URLField()),
            ],
        ),
    ]
